import { formatLongDate, formatMonth, localDateKey } from './utils/date-utils.js'
import { createSupabaseClient } from './services/supabase-client.js'
import { addCheckin, bucketCategories, bucketStatuses, createMemoryDraftFromBucket, deleteBucketItem, deleteMemory, getCheckinStatus, loadState, moods, openReveal, persistState, saveBucketItem, saveMemory, updateBucketStatus } from './services/between-us-store.js'

const app = document.querySelector('#app')
let state = loadState()
let modal = ''
let toast = ''
let bucketFilter = 'alle'
let onboardingStep = 0
let supabaseStatus = { isConfigured: false, message: 'Supabase wird geprüft.' }
const onboarding = [
  ['Euer privater Raum.', 'Ein Ort für tägliche Nähe, schöne Erinnerungen und gemeinsame Wünsche.'],
  ['Paar verbinden', 'Erstellt einen privaten Paarraum oder gebt einen Einladungscode ein.'],
  ['Das tägliche Ritual', 'Beantwortet jeden Tag eine Frage. Eure Antworten werden sichtbar, sobald ihr beide geantwortet habt.'],
  ['Ein Moment pro Tag', 'Nicht alles. Nur das, was bleiben soll.'],
  ['Gemeinsame Wünsche', 'Sammelt Dates, Reisen, Rituale und Ziele, die ihr gemeinsam erleben möchtet.'],
]

function commit(message) { persistState(state); toast = message || ''; render(); if (toast) setTimeout(() => { toast = ''; render() }, 2600) }
function esc(value='') { return String(value).replace(/[&<>"']/g, (m) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])) }
function viewTitle() { return state.activeView === 'today' ? 'Heute' : state.activeView === 'memories' ? 'Memorys' : 'Bucketlist' }

async function initSupabase() {
  const { client, config } = await createSupabaseClient()
  window.betweenUsSupabase = client
  supabaseStatus = { isConfigured: Boolean(client), message: config.message }
  render()
}

function render() {
  app.dataset.theme = state.theme
  app.innerHTML = state.onboarded ? shell() : onboardingView()
  bind()
}

function shell() { return `<main class="screen"><div class="topbar"><div><div class="eyebrow">Between Us</div><h2>${viewTitle()}</h2><small>${supabaseStatus.isConfigured ? 'Supabase konfiguriert' : 'Demo-Modus'}</small></div><button class="btn ghost" data-action="theme" aria-label="Theme wechseln">${state.theme === 'dark' ? 'Hell' : 'Dunkel'}</button></div>${state.activeView === 'today' ? todayView() : state.activeView === 'memories' ? memoriesView() : bucketView()}</main>${nav()}${modal}${toast ? `<div class="toast" role="status">${toast}</div>` : ''}` }
function nav() { return `<nav class="bottom-nav" aria-label="Hauptnavigation">${[['today','Heute','◐'],['memories','Memorys','◇'],['bucket','Bucketlist','＋']].map(([id,label,icon]) => `<button class="nav-item ${state.activeView===id?'active':''}" data-view="${id}"><span aria-hidden="true">${icon}</span><span>${label}</span></button>`).join('')}</nav>` }

function onboardingView() { const [title,text] = onboarding[onboardingStep]; return `<main class="screen stack"><div class="hero-orb" aria-hidden="true"></div><section class="card stack"><div class="eyebrow">Schritt ${onboardingStep+1} von ${onboarding.length}</div><h1>${title}</h1><p>${text}</p>${onboardingStep===1 ? `<div class="card"><strong>Einladungscode</strong><h2>${state.pair.inviteCode}</h2><label class="field">Code eingeben<input id="invite" placeholder="z. B. US-4287" /></label></div>`:''}<div class="grid2"><button class="btn secondary" data-action="skip">Überspringen</button><button class="btn" data-action="next-onboarding">${onboardingStep===0?'Gemeinsam starten':onboardingStep===onboarding.length-1?'Zum Check-in':'Weiter'}</button></div></section></main>` }

function todayView() { const status = getCheckinStatus(state); const memory = state.memories.find((m) => m.date === localDateKey()); const inspiration = state.bucketItems.find((i) => i.status !== 'erlebt') || state.bucketItems[0]; return `<section class="stack"><p>${formatLongDate(state.dailyQuestion.date)} · Schön, dass ihr euch heute Zeit füreinander nehmt.</p><article class="card stack"><div class="eyebrow">Tagesfrage</div><h2>${state.dailyQuestion.text}</h2>${checkinStatus(status)}${!status.me ? checkinForm() : ''}${status.bothAnswered && !status.revealOpen ? `<button class="btn" data-action="reveal">Gemeinsamen Reveal öffnen</button>` : ''}${status.revealOpen ? revealView(status) : ''}${status.me && !status.partner ? `<button class="btn ghost" data-action="simulate">Demo: Partnerantwort simulieren</button>` : ''}</article><article class="card"><div class="eyebrow">Memory des Tages</div>${memory ? `<h3>${esc(memory.title)}</h3><p>${esc(memory.text)}</p><button class="btn secondary" data-edit-memory="${memory.id}">Öffnen</button>` : `<p>Noch kein Moment gespeichert. Ein Memory pro Tag reicht.</p><button class="btn secondary" data-new-memory="today">Memory anlegen</button>`}</article><article class="card"><div class="eyebrow">Leise Inspiration</div><h3>${esc(inspiration?.title || 'Ein kleiner Wunsch für euch')}</h3><p>Wunsch → Erlebnis → Erinnerung</p></article>${state.pair.streak > 1 ? `<p>Ihr habt euch an ${state.pair.streak} Tagen in Folge kurz Zeit genommen — ganz ohne Druck.</p>` : ''}</section>` }
function checkinStatus(s) { if (!s.me && !s.partner) return `<div class="status-row"><div class="status-pill">Du: offen</div><div class="status-pill">Partnerperson: offen</div></div>`; if (s.me && !s.partner) return `<div class="card">Deine Antwort ist sicher gespeichert. Warte noch auf die Antwort deiner Partnerperson.</div>`; if (!s.me && s.partner) return `<div class="card">Die Antwort deiner Partnerperson ist da. Deine fehlt noch.</div>`; return `<div class="card">Eure Antworten sind da.</div>` }
function checkinForm() { return `<form class="stack" id="checkin-form"><div class="chips">${moods.map((m,i)=>`<button type="button" class="chip ${i===0?'active':''}" data-mood="${m}">${m}</button>`).join('')}</div><input type="hidden" name="mood" value="verbunden" /><label class="field">Deine Antwort<textarea name="text" required placeholder="Ein paar ehrliche Sätze genügen."></textarea></label><button class="btn">Antwort geschützt speichern</button></form>` }
function revealView(s) { return `<div class="grid2"><article class="card"><strong>Du</strong><p>${esc(s.me.text)}</p><small>${esc(s.me.mood)}</small></article><article class="card"><strong>Partnerperson</strong><p>${esc(s.partner.text)}</p><small>${esc(s.partner.mood)}</small></article></div><div class="chips">${['Das bedeutet mir viel','Danke','Umarmung','Lass uns darüber sprechen'].map(r=>`<button class="chip" data-reaction="${r}">${r}</button>`).join('')}</div>` }

function memoriesView() { const groups = [...state.memories].sort((a,b)=>b.date.localeCompare(a.date)).reduce((acc,m)=>{(acc[formatMonth(m.date)] ||= []).push(m); return acc},{}); return `<section class="stack"><button class="btn" data-new-memory="blank">Neues Memory</button>${state.memories.length ? `<div class="timeline">${Object.entries(groups).map(([month,items])=>`<div><div class="month">${month}</div>${items.map(m=>`<article class="card memory-card"><small>${formatLongDate(m.date)}</small><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p><div class="chips"><button class="chip" data-edit-memory="${m.id}">Bearbeiten</button><button class="chip" data-delete-memory="${m.id}">Löschen</button></div></article>`).join('')}</div>`).join('')}</div>` : `<div class="empty"><h3>Noch keine Memorys</h3><p>Speichert einen Moment, der bleiben soll.</p></div>`}</section>` }

function bucketView() { const items = state.bucketItems.filter(i => bucketFilter === 'alle' || i.status === bucketFilter); return `<section class="stack"><div class="segment"><button class="${bucketFilter==='alle'?'active':''}" data-filter="alle">Alle</button>${bucketStatuses.map(s=>`<button class="${bucketFilter===s?'active':''}" data-filter="${s}">${s}</button>`).join('')}</div><button class="btn" data-edit-bucket="new">Wunsch hinzufügen</button>${items.map(i=>`<article class="card stack"><div class="eyebrow">${esc(i.category)} · ${esc(i.status)}</div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><div class="chips">${bucketStatuses.map(s=>`<button class="chip ${i.status===s?'active':''}" data-status="${i.id}|${s}">${s}</button>`).join('')}</div><div class="chips"><button class="chip" data-edit-bucket="${i.id}">Bearbeiten</button>${i.status==='erlebt'?`<button class="chip" data-bucket-memory="${i.id}">Memory erstellen</button>`:''}<button class="chip" data-delete-bucket="${i.id}">Löschen</button></div></article>`).join('') || `<div class="empty">Hier ist noch Raum für gemeinsame Wünsche.</div>`}</section>` }

function memoryModal(memory = { date: localDateKey(), title:'', text:'', mood:'verbunden', image:'', bucketItemId:'' }) { modal = `<div class="modal"><form class="card stack" id="memory-form"><h2>Memory speichern</h2><input name="id" type="hidden" value="${memory.id||''}" /><label class="field">Datum<input name="date" type="date" value="${memory.date}" /></label><label class="field">Titel<input name="title" value="${esc(memory.title)}" required /></label><label class="field">Was soll bleiben?<textarea name="text" required>${esc(memory.text)}</textarea></label><label class="field">Stimmung<select name="mood">${moods.map(m=>`<option ${memory.mood===m?'selected':''}>${m}</option>`)}</select></label><input name="image" type="hidden" value="${memory.image||''}" /><input name="bucketItemId" type="hidden" value="${memory.bucketItemId||''}" /><div class="grid2"><button class="btn secondary" type="button" data-action="close">Abbrechen</button><button class="btn">Speichern</button></div></form></div>`; render() }
function bucketModal(item = { title:'', description:'', category:'Dates', status:'Wunsch', targetDate:'', place:'' }) { modal = `<div class="modal"><form class="card stack" id="bucket-form"><h2>Gemeinsamer Wunsch</h2><input name="id" type="hidden" value="${item.id||''}" /><label class="field">Titel<input name="title" value="${esc(item.title)}" required /></label><label class="field">Beschreibung<textarea name="description">${esc(item.description)}</textarea></label><label class="field">Kategorie<select name="category">${bucketCategories.map(c=>`<option ${item.category===c?'selected':''}>${c}</option>`)}</select></label><label class="field">Status<select name="status">${bucketStatuses.map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`)}</select></label><label class="field">Zieldatum<input name="targetDate" type="date" value="${item.targetDate||''}" /></label><label class="field">Ort<input name="place" value="${esc(item.place||'')}" /></label><div class="grid2"><button class="btn secondary" type="button" data-action="close">Abbrechen</button><button class="btn">Speichern</button></div></form></div>`; render() }

function bind() { document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.activeView=b.dataset.view; commit()}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action)); document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('.chip').forEach(c=>c.classList.remove('active')); b.classList.add('active'); document.querySelector('[name="mood"]').value=b.dataset.mood}); document.querySelector('#checkin-form')?.addEventListener('submit', e=>{e.preventDefault(); try{addCheckin(state,Object.fromEntries(new FormData(e.target))); commit('Deine Antwort ist sicher gespeichert.')}catch(err){commit(err.message)}}); document.querySelector('#memory-form')?.addEventListener('submit', e=>{e.preventDefault(); try{saveMemory(state,Object.fromEntries(new FormData(e.target))); modal=''; state.activeView='memories'; commit('Euer Moment des Tages ist gespeichert.')}catch(err){commit(err.message)}}); document.querySelector('#bucket-form')?.addEventListener('submit', e=>{e.preventDefault(); try{saveBucketItem(state,Object.fromEntries(new FormData(e.target))); modal=''; commit('Euer Wunsch ist gespeichert.')}catch(err){commit(err.message)}}); document.querySelectorAll('[data-new-memory]').forEach(b=>b.onclick=()=>{const existing=state.memories.find(m=>m.date===localDateKey()); memoryModal(existing || undefined)}); document.querySelectorAll('[data-edit-memory]').forEach(b=>b.onclick=()=>memoryModal(state.memories.find(m=>m.id===b.dataset.editMemory))); document.querySelectorAll('[data-delete-memory]').forEach(b=>b.onclick=()=>{if(confirm('Dieses Memory wirklich löschen?')){deleteMemory(state,b.dataset.deleteMemory);commit('Memory gelöscht.')}}); document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{bucketFilter=b.dataset.filter;render()}); document.querySelectorAll('[data-edit-bucket]').forEach(b=>b.onclick=()=>bucketModal(b.dataset.editBucket==='new'?undefined:state.bucketItems.find(i=>i.id===b.dataset.editBucket))); document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{const [id,s]=b.dataset.status.split('|'); updateBucketStatus(state,id,s); commit(s==='erlebt'?'Aus Wunsch wird Erlebnis.':'Status aktualisiert.')}); document.querySelectorAll('[data-delete-bucket]').forEach(b=>b.onclick=()=>{if(confirm('Diesen Wunsch wirklich löschen?')){deleteBucketItem(state,b.dataset.deleteBucket);commit('Wunsch gelöscht.')}}); document.querySelectorAll('[data-bucket-memory]').forEach(b=>b.onclick=()=>memoryModal(createMemoryDraftFromBucket(state.bucketItems.find(i=>i.id===b.dataset.bucketMemory)))) }
function action(a) { if(a==='theme'){state.theme=state.theme==='dark'?'light':'dark'; commit()} if(a==='skip'){state.onboarded=true; commit()} if(a==='next-onboarding'){onboardingStep++; if(onboardingStep>=onboarding.length){state.onboarded=true; onboardingStep=0} commit()} if(a==='simulate'){addCheckin(state,{userId:'partner',mood:'dankbar',text:'Ich habe heute gemerkt, wie gut mir deine Ruhe tut.'}); commit('Demo-Partnerantwort ist eingetroffen.')} if(a==='reveal'){openReveal(state); commit('Eure Antworten sind geöffnet.')} if(a==='close'){modal=''; render()} }
render()
initSupabase()
